# Generated by Django 2.0.4 on 2018-04-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribble', '0004_auto_20180425_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
