# Generated by Django 2.0.4 on 2018-04-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribble', '0011_auto_20180426_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
