# Generated by Django 2.0.4 on 2018-04-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scribble', '0003_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='photo_url',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
